[package]
name = "core-mx-bridge-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.core-mx-bridge-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.49.0"
default-features = false
