[package]
name = "core-mx-bridge-sc-meta"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies.core-mx-bridge-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.3"
default-features = false
