// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           30
// Async Callback (empty):               1
// Total number of exported functions:  33

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    core_mx_bridge_sc
    (
        init => init
        upgrade => upgrade
        sendToLiquidity => send_to_liquidity
        sendFromLiquidity => send_from_liquidity
        getLiquidity => liquidity
        getTokenDecimals => token_decimals
        getMinimumDeposit => minimum_deposit
        getMaximumDeposit => maximum_deposit
        getFeeCollector => fee_colector
        getFeeValue => fee_value
        getWegldContractAddress => wegld_contract_address
        setAdministrator => set_administrator
        getAdministrator => administrator
        getTokensWhitelist => tokens_whitelist
        getWhitelistState => whitelist_state
        getContractState => contract_state
        getRelayer => relayer
        setContractStateActive => set_contract_state_active
        setContractStateInactive => set_contract_state_inactive
        setWhitelistStateActive => set_whitelist_state_active
        setWhitelistStateInactive => set_whitelist_state_inactive
        setDepositLimits => set_deposit_limits
        setFeeCollector => set_fee_collector
        setFeeValue => set_fee_value
        setWegldContractAddress => set_wegld_contract_address
        addTokensToWhitelist => add_tokens_to_whitelist
        removeTokensFromWhitelist => remove_tokens_from_whitelist
        addToWhitelist => add_to_whitelist
        removeFromWhitelist => remove_from_whitelist
        setRelayer => set_relayer
        addToLiquidity => add_to_liquidity
        removeFromLiquidity => remove_from_liquidity
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
