// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           21
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    core_mx_bridge_sc
    (
        init => init
        upgrade => upgrade
        sendToLiquidity => send_to_liquidity
        sendFromLiquidity => send_from_liquidity
        getLiquidity => liquidity
        getMinimumDeposit => minimum_deposit
        getMaximumDeposit => maximum_deposit
        setAdministrator => set_administrator
        getAdministrator => administrator
        getTokensWhitelist => tokens_whitelist
        getContractState => contract_state
        getRelayer => relayer
        setContractStateActive => set_contract_state_active
        setContractStateInactive => set_contract_state_inactive
        setWhitelistStateActive => set_whitelist_state_active
        setDepositLimits => set_deposit_limits
        setWhitelistStateInactive => set_whitelist_state_inactive
        addTokensToWhitelist => add_tokens_to_whitelist
        removeTokensFromWhitelist => remove_tokens_from_whitelist
        setRelayer => set_relayer
        addToLiquidity => add_to_liquidity
        removeFromLiquidity => remove_from_liquidity
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
